version: "3.9"
   
services:
  db:
    image: postgres
    # volumes:
      # - /var/lib/postgresql/data
      # - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # command: sh -c "pg_ctl -D /var/lib/postgresql/data -l logfile start"
# pg_ctl -D /var/lib/postgresql/data -l logfile start

  web:
    build: .
    command: sh -c "pip install -r requirements.txt && ./manage.py migrate && python3 manage.py collectstatic && ./manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
